Beta Front-End Combination
aedanmc/travelo-hey pull request #73
Opened 2022-05-12 01:26 UTC by matthewdbroom13

Includes all of the code for the beta release. Many aspects of this will be changed between now and the final release.

2022-05-12 01:44 UTC, C-Christensen requested changes
You are running the build using the old set up. You might want to update this before merging this branch.

2022-05-12 01:58 UTC, C-Christensen approved these changes
LGTM

2022-05-12 03:55 UTC, mik3ycodez approved these changes

2022-05-13 03:28 UTC, aedanmc approved these changes
I am approving this so we can merge it to main and start "fresh" post-beta. Something that I would like to see for this and all front end code are:

- Javadoc-style comments explaining the general purpose of a component
- Refactoring of all code not related to the primary purpose of the component, such as data fetching
- Some testing to ensure that the high level functionality of each component is working as intended.

2022-05-13 21:58 UTC, merged